import streamlit as st
import pandas as pd
import google.generativeai as genai
import re

st.set_page_config(page_title="Chat with Data", layout="wide")

def execute_llm_code(code, df):
    """Safely executes the code generated by Gemini."""
    try:
        # Create a local namespace for execution
        local_vars = {'df': df, 'pd': pd}
        exec(code, {}, local_vars)
        return local_vars.get('result', "I've processed your request."), local_vars.get('fig', None)
    except Exception as e:
        return f"Error executing code: {e}", None

if 'df' in st.session_state:
    df = st.session_state['df']
    st.title("💬 Chat with DataTalk")
    st.info("Ask questions like: 'Show me the correlation between price and sales' or 'What is the average age?'")

    user_query = st.chat_input("Enter your question here...")

    if user_query:
        # Prompt Engineering [cite: 143]
        prompt = f"""
        You are a data expert. Dataset has columns: {list(df.columns)}.
        User Query: {user_query}
        
        Write Python code using 'df'. 
        - Store text answers in a variable named 'result'.
        - If a chart is needed, use Plotly and store it in 'fig'.
        - Return ONLY the code block.
        """
        
        # Configure Gemini [cite: 92]
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        with st.spinner("Analyzing..."):
            response = model.generate_content(prompt)
            # Extract code from Markdown blocks
            code_match = re.search(r"```python\n(.*?)```", response.text, re.DOTALL)
            
            if code_match:
                code = code_match.group(1)
                ans, fig = execute_llm_code(code, df)
                
                st.write(ans)
                if fig:
                    st.plotly_chart(fig, use_container_width=True)
            else:
                st.write(response.text)

else:
    st.error("No dataset found. Please go to the Upload page.")